### ISSUE TITLE
ЯКОРЯ - 4 шт создать

### ISSUE THREAD

**Issue by canej** [plasticrestore/plasticrestore.github.io#7]
нужны ссылки на 4 любых места страницы:
на наши работы
1. Укажем на ремонт БАМПЕРОВ - Автопластик - на фото или примерно в то место
2 "Мото-пластик" - то сто ремонтируем мотопластик
3 ссылка "на подвал" укажем что "можете заказеть обратный звонок"
4 раздел "О нас" укажем на то что делаем "- БЕЗ сеток и пр"

**Comment by webcane** [comment]
- #bamper-remont
- #moto-plastic
- #callback
- #bez-setok-remont

**Comment by webcane** [comment]
В конечном счете заменил якоря на id. Переходы работают норм.
Дальше подрубай в метрику.
